INSERT INTO skills (name, description, skill_type, category, tier, position, effects_per_rank, scaling_stat) VALUES 
('Power Strike', 'Deal 150% weapon damage', 'active', 'combat', 1, 1, '{"damage": 150}', 'strength'),
('Rending Blow', 'Deal 120% + bleed (5s)', 'active', 'combat', 2, 1, '{"damage": 120}', 'strength'),
('Brutal Swing', 'AoE 100% damage, 3 targets', 'active', 'combat', 2, 1, '{"damage": 100}', 'strength'),
('Weapon Mastery', '+5% weapon damage', 'passive', 'combat', 1, 1, '{"bonus": 5}', 'strength'),
('Armor Breaker', 'Deal 130%, reduce armor 20%', 'active', 'combat', 3, 1, '{"damage": 130}', 'strength'),
('Berserker Rage', '+30% damage, -15% defense (10s)', 'active', 'combat', 4, 1, '{"damage": 130}', 'strength'),
('Execute', 'Deal 200% to targets <30% HP', 'active', 'combat', 4, 1, '{"damage": 200}', 'strength'),
('Titan Grip', 'Two-hand weapons gain +15% damage', 'passive', 'combat', 3, 1, '{"bonus": 15}', 'strength'),
('Counterattack', '20% chance to counter on block', 'passive', 'combat', 5, 1, '{"chance": 20}', 'agility'),
('Overwhelm', 'Stun 2s + 180% damage', 'active', 'combat', 5, 1, '{"damage": 180}', 'strength'),
('Battle Cry', '+10% damage to self and allies (15s)', 'active', 'combat', 3, 1, '{"bonus": 10}', 'strength'),
('Heavy Impact', 'Crits stagger enemies 1s', 'passive', 'combat', 2, 1, '{"bonus": 1}', 'strength'),
('Relentless', 'Kills reset cooldowns by 2s', 'passive', 'combat', 4, 1, '{"bonus": 2}', 'strength'),
('Warrior Endurance', '+10% max HP', 'passive', 'combat', 3, 1, '{"bonus": 10}', 'vitality'),
('Decimation', '400% damage, ignores 50% armor', 'ultimate', 'combat', 6, 1, '{"damage": 400}', 'strength'),
('Shadow Strike', 'Deal 130% + 10% crit chance', 'active', 'shadow', 1, 1, '{"damage": 130}', 'agility'),
('Stealth', 'Invisible 10s, next attack +50%', 'active', 'shadow', 2, 1, '{"damage": 50}', 'agility'),
('Backstab', '200% from behind', 'active', 'shadow', 3, 1, '{"damage": 200}', 'agility'),
('Evasion', '+3% dodge chance', 'passive', 'shadow', 1, 1, '{"bonus": 3}', 'agility'),
('Poison Blade', 'Attacks apply poison 5s', 'active', 'shadow', 2, 1, '{"bonus": 5}', 'cunning'),
('Smoke Bomb', 'AoE blind 3s, self +20% dodge', 'active', 'shadow', 3, 1, '{"bonus": 20}', 'agility'),
('Assassinate', '300% to targets <20% HP', 'active', 'shadow', 5, 1, '{"damage": 300}', 'agility'),
('Fleet Footed', '+10% movement, +5% dodge', 'passive', 'shadow', 2, 1, '{"bonus": 10}', 'agility'),
('Shadow Dance', '3 rapid strikes at 80% each', 'active', 'shadow', 4, 1, '{"damage": 80}', 'agility'),
('Exploit Weakness', '+15% damage to debuffed', 'passive', 'shadow', 3, 1, '{"bonus": 15}', 'cunning'),
('Vanishing Act', 'Remove threat, stealth 5s', 'active', 'shadow', 4, 1, '{"bonus": 5}', 'agility'),
('Blade Flurry', '5 hits at 50% to random', 'active', 'shadow', 3, 1, '{"damage": 50}', 'agility'),
('Lethal Precision', '+20% crit damage', 'passive', 'shadow', 4, 1, '{"bonus": 20}', 'agility'),
('Shadow Walk', 'Stealth remains on move', 'passive', 'shadow', 5, 1, '{"bonus": 1}', 'agility'),
('Deaths Embrace', '500% + execute <25%', 'ultimate', 'shadow', 6, 1, '{"damage": 500}', 'agility'),
('Crimson Slash', 'Deal 120% + heal 10%', 'active', 'blood', 1, 1, '{"damage": 120}', 'vitality'),
('Blood Shield', 'Absorb 20% max HP', 'active', 'blood', 2, 1, '{"bonus": 20}', 'vitality'),
('Life Tap', 'Sacrifice 10% HP for 15% mana', 'active', 'blood', 2, 1, '{"bonus": 15}', 'spirit'),
('Sanguine Aura', '+5% life steal', 'passive', 'blood', 1, 1, '{"bonus": 5}', 'vitality'),
('Blood Boil', '+25% damage, -5% HP/s', 'active', 'blood', 3, 1, '{"bonus": 25}', 'vitality'),
('Vampiric Touch', 'Deal 100%, heal 50%', 'active', 'blood', 3, 1, '{"damage": 100}', 'vitality'),
('Crimson Pact', 'Below 50% HP: +15% damage', 'passive', 'blood', 3, 1, '{"bonus": 15}', 'vitality'),
('Blood Rage', 'Kills heal 10% HP', 'active', 'blood', 4, 1, '{"bonus": 10}', 'vitality'),
('Hemorrhage', 'Heavy bleed 3% max HP/s', 'active', 'blood', 4, 1, '{"bonus": 3}', 'cunning'),
('Undying Will', 'Survive lethal at 1 HP', 'passive', 'blood', 4, 1, '{"bonus": 1}', 'vitality'),
('Sanguine Burst', 'AoE 150%, heal per hit', 'active', 'blood', 5, 1, '{"damage": 150}', 'vitality'),
('Blood Bond', 'Share 30% damage taken', 'active', 'blood', 3, 1, '{"bonus": 30}', 'cunning'),
('Transfusion', '20% overheal to shield', 'passive', 'blood', 2, 1, '{"bonus": 20}', 'vitality'),
('Crimson Tide', 'Life steal +1% per 10% missing', 'passive', 'blood', 5, 1, '{"bonus": 1}', 'vitality'),
('Exsanguinate', '400% + heal full', 'ultimate', 'blood', 6, 1, '{"damage": 400}', 'vitality'),
('Void Bolt', 'Deal 110% shadow damage', 'active', 'void', 1, 1, '{"damage": 110}', 'cunning'),
('Corruption', 'DoT: 20% over 8s', 'active', 'void', 2, 1, '{"damage": 20}', 'cunning'),
('Curse Weakness', 'Enemy -20% damage', 'active', 'void', 2, 1, '{"bonus": 20}', 'cunning'),
('Dark Affinity', '+5% shadow damage', 'passive', 'void', 1, 1, '{"bonus": 5}', 'cunning'),
('Soul Drain', 'Channel 30% dmg/s, heal 50%', 'active', 'void', 3, 1, '{"damage": 30}', 'cunning'),
('Void Prison', 'Stun 3s, +20% dmg taken', 'active', 'void', 3, 1, '{"bonus": 20}', 'cunning'),
('Entropy', 'DoTs tick 15% faster', 'passive', 'void', 3, 1, '{"bonus": 15}', 'cunning'),
('Shadow Nova', 'AoE 130% + Corruption', 'active', 'void', 4, 1, '{"damage": 130}', 'cunning'),
('Wither', '-30% healing received', 'active', 'void', 4, 1, '{"bonus": 30}', 'cunning'),
('Void Walker', '+10% dmg, +10% dmg taken', 'passive', 'void', 4, 1, '{"bonus": 10}', 'cunning'),
('Mind Shatter', '180% + confuse 5s', 'active', 'void', 5, 1, '{"damage": 180}', 'cunning'),
('Creeping Doom', 'DoTs spread on death', 'passive', 'void', 2, 1, '{"bonus": 1}', 'cunning'),
('Null Zone', 'AoE field: -25% enemy dmg', 'active', 'void', 5, 1, '{"bonus": 25}', 'cunning'),
('Inevitable End', 'DoT crits deal 2x dmg', 'passive', 'void', 5, 1, '{"bonus": 2}', 'cunning'),
('Void Eruption', '500% AoE + detonate DoTs', 'ultimate', 'void', 6, 1, '{"damage": 500}', 'cunning'),
('Arcane Bolt', 'Deal 120% arcane', 'active', 'arcane', 1, 1, '{"damage": 120}', 'spirit'),
('Mana Shield', 'Absorb dmg using mana', 'active', 'arcane', 2, 1, '{"bonus": 1}', 'spirit'),
('Arcane Infusion', '+5% spell dmg', 'passive', 'arcane', 1, 1, '{"bonus": 5}', 'spirit'),
('Frost Lance', '110% + slow 30%', 'active', 'arcane', 2, 1, '{"damage": 110}', 'spirit'),
('Flame Burst', '100% + burn 10%', 'active', 'arcane', 2, 1, '{"damage": 100}', 'spirit'),
('Spell Surge', 'Crits refund 20% mana', 'passive', 'arcane', 3, 1, '{"bonus": 20}', 'spirit'),
('Chain Lightning', '90% to 4 targets', 'active', 'arcane', 3, 1, '{"damage": 90}', 'spirit'),
('Arcane Explosion', 'AoE 150%', 'active', 'arcane', 4, 1, '{"damage": 150}', 'spirit'),
('Time Warp', 'Reset CDs, +50% haste', 'active', 'arcane', 4, 1, '{"bonus": 50}', 'spirit'),
('Elemental Mastery', '+10% elemental dmg', 'passive', 'arcane', 3, 1, '{"bonus": 10}', 'spirit'),
('Meteor', '250% AoE', 'active', 'arcane', 5, 1, '{"damage": 250}', 'spirit'),
('Mana Burn', 'Drain 30% enemy mana', 'active', 'arcane', 4, 1, '{"bonus": 30}', 'spirit'),
('Brilliance', '+30% mana regen', 'passive', 'arcane', 5, 1, '{"bonus": 30}', 'spirit'),
('Arcane Barrage', '3 bolts 100% each', 'active', 'arcane', 5, 1, '{"damage": 100}', 'spirit'),
('Singularity', '600% AoE implosion', 'ultimate', 'arcane', 6, 1, '{"damage": 600}', 'spirit'),
('Second Wind', 'Heal 20% max HP', 'active', 'survival', 1, 1, '{"bonus": 20}', 'vitality'),
('Stone Skin', '+30% armor', 'active', 'survival', 2, 1, '{"bonus": 30}', 'vitality'),
('Fortitude', '+5% max HP', 'passive', 'survival', 1, 1, '{"bonus": 5}', 'vitality'),
('Cleanse', 'Remove 1 debuff', 'active', 'survival', 2, 1, '{"bonus": 1}', 'spirit'),
('Evasive Roll', 'Dodge next attack', 'active', 'survival', 2, 1, '{"bonus": 1}', 'agility'),
('Iron Will', '+20% CC resist', 'passive', 'survival', 3, 1, '{"bonus": 20}', 'vitality'),
('Emergency Heal', 'Auto-heal 30% at <15%', 'passive', 'survival', 4, 1, '{"bonus": 30}', 'vitality'),
('Last Stand', 'Immune 4s at 1 HP', 'active', 'survival', 4, 1, '{"bonus": 4}', 'vitality'),
('Natural Recovery', '+50% HP regen OOC', 'passive', 'survival', 3, 1, '{"bonus": 50}', 'vitality'),
('Indomitable', 'Full heal + immune 3s', 'ultimate', 'survival', 5, 1, '{"bonus": 100}', 'vitality'),
('Keen Eye', '+5% drop rate', 'passive', 'utility', 1, 1, '{"bonus": 5}', 'luck'),
('Swift Hands', '+10% gathering speed', 'passive', 'utility', 1, 1, '{"bonus": 10}', 'agility'),
('Treasure Hunter', '+10% gold find', 'passive', 'utility', 2, 1, '{"bonus": 10}', 'luck'),
('Explorer Instinct', 'Reveal hidden objects', 'passive', 'utility', 2, 1, '{"bonus": 1}', 'cunning'),
('Merchant Eye', '+10% sell prices', 'passive', 'utility', 3, 1, '{"bonus": 10}', 'luck'),
('Master Gatherer', '+15% gather yield', 'passive', 'utility', 3, 1, '{"bonus": 15}', 'luck'),
('Lucky Strike', '5% double loot', 'passive', 'utility', 4, 1, '{"bonus": 5}', 'luck'),
('Pathfinder', '+15% move speed', 'passive', 'utility', 2, 1, '{"bonus": 15}', 'agility'),
('Scrounger', 'Extra materials', 'passive', 'utility', 4, 1, '{"bonus": 1}', 'luck'),
('Fortune Favor', '+5% luck rolls', 'passive', 'utility', 5, 1, '{"bonus": 5}', 'luck'),
('Void Step', 'Teleport, next +100%', 'legendary', 'shadow', 10, 1, '{"bonus": 100}', 'agility'),
('Sanguine Covenant', 'Lifesteal on DoTs', 'legendary', 'blood', 10, 1, '{"bonus": 1}', 'vitality'),
('Soul Harvest', '+5% dmg stack', 'legendary', 'cunning', 10, 1, '{"bonus": 5}', 'cunning'),
('Ethereal Form', 'Invulnerable 3s, +50% dmg', 'legendary', 'agility', 10, 1, '{"bonus": 50}', 'agility'),
('Doom Blade', '350% + apply DoTs', 'legendary', 'cunning', 10, 1, '{"damage": 350}', 'cunning'),
('Phoenix Rebirth', 'Revive at 50% HP', 'legendary', 'vitality', 10, 1, '{"bonus": 50}', 'vitality'),
('Time Stop', 'Freeze all 3s', 'legendary', 'spirit', 10, 1, '{"bonus": 3}', 'spirit'),
('Abyssal Gaze', 'See stealth, +20% dmg', 'legendary', 'cunning', 10, 1, '{"bonus": 20}', 'cunning'),
('Reality Tear', 'AoE ignore armor', 'legendary', 'spirit', 10, 1, '{"damage": 200}', 'spirit'),
('Godslayer', '1000% to bosses', 'legendary', 'combat', 10, 1, '{"damage": 1000}', 'strength') ON CONFLICT DO NOTHING;